#ifndef GUARD_CONSTANTS_LAYOUTS_H
#define GUARD_CONSTANTS_LAYOUTS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/layouts/layouts.json
//

#define LAYOUT_FAREWARD 1
#define LAYOUT_PLAYER_HOUSE1F 2
#define LAYOUT_PLAYER_HOUSE2F 3
#define LAYOUT_HALEY_HOUSE1F 4
#define LAYOUT_HALEY_HOUSE2F 5
#define LAYOUT_DAMON_HOUSE1F 6
#define LAYOUT_DAMON_HOUSE_DAMONS_ROOM 7
#define LAYOUT_FAREWARD_HOUSE1 8
#define LAYOUT_FAREWARD_HOUSE2 9
#define LAYOUT_ROUTE249 10
#define LAYOUT_ROUTE250 11
#define LAYOUT_REMUS 12

#endif // GUARD_CONSTANTS_LAYOUTS_H
