FarewardHouse1_MapScripts::
	.byte 0


FarewardHouse1_EventScript_Woman::
# 6 "data/maps/FarewardHouse1/scripts.pory"
	msgbox FarewardHouse1_Text_Woman, MSGBOX_NPC
	return


FarewardHouse1_EventScript_Man::
# 10 "data/maps/FarewardHouse1/scripts.pory"
	msgbox FarewardHouse1_Text_Man, MSGBOX_NPC
	return


FarewardHouse1_Text_Woman::
# 13 "data/maps/FarewardHouse1/scripts.pory"
	.string "Such a beautiful day! My little yamper\n"
	.string "will be so excited to go for a walk\l"
	.string "in this weather.$"

FarewardHouse1_Text_Man::
# 19 "data/maps/FarewardHouse1/scripts.pory"
	.string "Fareward is such a lovely, quiet town. I'm\n"
	.string "so glad we decided to settle down here.$"
