DamonHouseDamonsRoom_MapScripts::
	.byte 0


DamonHouseDamonsRoom_EventScript_SwabluDoll::
# 6 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	lockall
# 7 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	msgbox DamonHouseDamonsRoom_Text_SwabluDoll
# 8 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	releaseall
	return


DamonHouseDamonsRoom_EventScript_GameCube::
# 12 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	lockall
# 13 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	msgbox DamonHouseDamonsRoom_Text_GameCube
# 14 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	releaseall
	return


DamonHouseDamonsRoom_EventScript_PC::
# 18 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	lockall
# 19 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	msgbox DamonHouseDamonsRoom_Text_PC
# 20 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	releaseall
	return


DamonHouseDamonsRoom_EventScript_Drawer::
# 24 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	lockall
# 25 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	msgbox DamonHouseDamonsRoom_Text_Drawer
# 26 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	releaseall
	return


DamonHouseDamonsRoom_Text_SwabluDoll::
# 29 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	.string "A swablu doll. Swablu always was one of\n"
	.string "Damon's favorites.$"

DamonHouseDamonsRoom_Text_GameCube::
# 34 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	.string "A Nintendo GameCube. I have lots of fond\n"
	.string "memories playing together with Damon.$"

DamonHouseDamonsRoom_Text_PC::
# 39 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	.string "Damon probably wouldn't mind me using\n"
	.string "his PC, but I don't know his password.$"

DamonHouseDamonsRoom_Text_Drawer::
# 44 "data/maps/DamonHouseDamonsRoom/scripts.pory"
	.string "There sure are lots of pokémon-related\n"
	.string "comic books in here!$"
